<?php
/**
 * Created by PhpStorm.
 * User: tieungao
 * Date: 2020-08-26
 * Time: 15:31
 */

namespace App\Http\Controllers\Admin;

use App\Models\Answer;
use App\Models\Company;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;
use Backpack\PermissionManager\app\Http\Controllers\UserCrudController;
use Illuminate\Support\Facades\DB;

class CustomUserCrudController extends UserCrudController
{
    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->crud->setEntityNameStrings('Người Dùng', 'Người Dùng');
        $this->crud->setRoute(backpack_url('custom-user'));
    }

    public function setupListOperation()
    {
        parent::setupListOperation();
        CRUD::addColumns([
            [
                'name' => 'display_role',
                'label' => 'Vai Trò'
            ],
            [
                // any type of relationship
                'name'         => 'company', // name of relationship method in the model
                'type'         => 'relationship',
                'label'        => 'Doanh Nghiệp', // Table column heading
                // OPTIONAL
                'entity'    => 'company', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model'     => Company::class, // foreign key model
            ],
            [
                'name' => 'filters',
                'label' => 'Các thuộc tính',
                'type' => 'table',
                'columns' => [
                    'att_id' => 'ID thuộc tính',
                    'att_value' => 'Giá trị'
                ],
            ],
        ]);

        CRUD::removeColumn('roles');
        CRUD::removeColumn('permissions');
        CRUD::removeFilter('role');
        CRUD::removeFilter('permissions');

        CRUD::addButtonFromView('line', 'clear_result', 'clear_result', 'end');


    }

    public function addUserFields()
    {
        //parent::addUserFields(); // TODO: Change the autogenerated stub


//        CRUD::modifyField('password', [
//            'name'  => 'password',
//            'label' => trans('backpack::permissionmanager.password'),
//            'type'  => 'password',
//            'attributes' => [
//                'autocomplete' => 'new-password'
//            ]
//        ]);

        CRUD::addFields([
            [
                'name'  => 'name',
                'label' => trans('backpack::permissionmanager.name'),
                'type'  => 'text',
            ],
            [
                'name'  => 'email',
                'label' => trans('backpack::permissionmanager.email'),
                'type'  => 'email',
            ],
            [
                'name'  => 'password',
                'label' => trans('backpack::permissionmanager.password'),
                'type'  => 'password',
            ],
            [
                'name'  => 'password_confirmation',
                'label' => trans('backpack::permissionmanager.password_confirmation'),
                'type'  => 'password',
            ]
        ]);

        CRUD::addFields([
            [  // Select
                'label'     => "Doanh Nghiệp",
                'type'      => 'select',
                'name'      => 'company_id', // the db column for the foreign key
                'entity'    => 'company',
                'model'     => "App\Models\Company", // related model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'options'   => (function ($query) {
                    return $query->orderBy('name', 'ASC')->get();
                }),
            ],
            [ // Table
                'name' => 'filters',
                'label' => 'Các thuộc tính',
                'type' => 'table',
                'entity_singular' => 'option', // used on the "Add X" button
                'columns' => [
                    'att_id' => 'ID thuộc tính',
                    'att_value' => 'Giá trị'
                ],
                'max' => 10, // maximum rows allowed in the table
                'min' => 1, // minimum rows allowed in the table
            ],
        ]);
    }

    public function setupUpdateOperation()
    {
        parent::setupUpdateOperation(); // TODO: Change the autogenerated stub
        CRUD::removeField('password');
        CRUD::removeField('password_confirmation');
    }

    public function clear($id)
    {
        Answer::where('user_id', $id)->delete();

        return redirect(url('admin/custom-user'));
    }
}